services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pantry
      POSTGRES_PASSWORD: pantry
    volumes:
        - /postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"