services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pantry
      POSTGRES_PASSWORD: pantry
    volumes:
        - /postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pantry@pantry.com
      PGADMIN_DEFAULT_PASSWORD: pantry
    ports:
        - "5050:80"
  
  cache:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'